# Generated by Django 2.2.1 on 2020-07-03 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example1',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='example1',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='example1',
            name='edad',
        ),
    ]
