# Generated by Django 2.2.1 on 2020-07-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0002_auto_20200702_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example1',
            name='direccion',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='example1',
            name='edad',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
