# Generated by Django 2.2.1 on 2020-07-03 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0003_auto_20200702_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='example1',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.CharField(max_length=255),
        ),
    ]
