# Generated by Django 2.2.1 on 2020-07-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0005_auto_20200703_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
