# Generated by Django 2.2.1 on 2020-07-04 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0007_remove_example1_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='example1',
            name='curp',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
