# Generated by Django 2.2.1 on 2020-07-04 03:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Example1', '0008_example1_curp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example1',
            name='curp',
            field=models.CharField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='example1',
            name='edad',
            field=models.IntegerField(max_length=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
